import { defineConfig } from "vitest/config"
import path from "path"

export default defineConfig({
  test: {
    globals: true,
    environment: "jsdom",
    include: ["tests/**/*.{test,spec}.{ts,tsx}"],
    exclude: ["node_modules", ".next", "out", "**/tests/visual/**", "**/tests/e2e/**"],
    coverage: {
      provider: "v8",
      reporter: ["text", "html", "lcov"],
      reportsDirectory: "./coverage",
      include: [
        "src/lib/**/*.{ts,tsx}",
        "src/utils/**/*.{ts,tsx}",
        "src/config/**/*.{ts,tsx}",
      ],
      exclude: [
        "node_modules/",
        "tests/",
        ".next/",
        "out/",
        "**/*.d.ts",
        "**/*.config.*",
        "**/types/**",
        "src/mockAPI/**",
        "src/test/**",
        "src/lib/database.types.ts",
        "src/lib/supabase/**",
        "src/lib/db/**",
        "src/lib/email-templates/**",
        "src/lib/errors/**",
        "src/lib/services/email-service.ts",
        "src/stores/**",
        "src/hooks/use-toast.ts",
        "src/lib/api/v2/artisansApi.ts",
        "src/lib/api/v2/interventionsApi.ts",
        "src/lib/api/v2/usersApi.ts",
        "src/lib/api/v2/tenantsApi.ts",
        "src/lib/api/v2/enumsApi.ts",
        "src/lib/api/v2/clientsApi.ts",
        "src/lib/api/v2/commentsApi.ts",
        "src/lib/api/v2/documentsApi.ts",
        "src/lib/api/v2/metiersApi.ts",
        "src/lib/api/v2/ownersApi.ts",
        "src/lib/api/v2/rolesApi.ts",
        "src/lib/api/v2/agenciesApi.ts",
        "src/lib/api/v2/reminders.ts",
        "src/lib/api/v2/search.ts",
        "src/lib/api/v2/index.ts",
        "src/lib/api/permissions.ts",
        "src/lib/api/interventions.ts",
        "src/lib/api/compta.ts",
        "src/lib/api/documents.ts",
        "src/lib/api/googleMaps.ts",
        "src/lib/api/invoice2go.ts",
        "src/lib/api/deepSearch.ts",
        "src/lib/api/artisans.ts",
        "src/lib/api/abort-controller-manager.ts",
        "src/lib/auth/**",
        "src/lib/supabase-api.ts",
        "src/lib/supabase-api-v2.ts",
        "src/lib/supabase-admin.ts",
        "src/lib/preload-critical-data.ts",
        "src/lib/themes.ts",
        "src/lib/device-capabilities.ts",
        "src/lib/navigation-tracker.ts",
        "src/lib/env.server.ts",
        "src/lib/insee-token.ts",
        "src/lib/preload-flag.ts",
        "src/lib/styled-components-registry.tsx",
        "src/lib/realtime/realtime-client.ts",
        "src/lib/realtime/broadcast-sync.ts",
        "src/lib/interventions/intervention-service.ts",
        "src/lib/interventions/owner-tenant-helpers.ts",
        "src/lib/interventions/status-chain-calculator.test.ts",
        "src/lib/services/statusProjection.ts",
        "src/lib/artisans/useArtisanDisplay.ts",
        "src/lib/artisans/index.ts",
        "src/lib/artisans/types.ts",
        "src/lib/comments/**",
        "src/lib/utils/encryption.ts",
        "src/lib/utils/navigation.ts",
        "src/lib/reference-api.ts",
        "src/lib/api/v2/statusesApi.ts",
        "src/lib/supabase-client.ts",
        "src/lib/interventions/status-updates.ts",
        "src/lib/interventions/status-display.ts",
        "src/lib/interventions/status-icons.tsx",
        "src/lib/interventions/status-chain-calculator.ts",
        "src/lib/query-keys.ts",
      ],
      thresholds: {
        global: {
          statements: 30,
          branches: 30,
          functions: 30,
          lines: 30,
        },
      },
    },
    setupFiles: ["./tests/setup.ts"],
  },
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "src"),
      "@/": path.resolve(__dirname, "src/"),
    },
  },
})
